name: Build Binary

on:
  push:
    branches: [branchMake, branchAutomake, master]
  pull_request:
    branches: [branchMake, branchAutomake, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Switch to branch with configure.ac
      run: git checkout branchAutomake

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool build-essential

    - name: Generate configure script
      run: autoreconf -i

    - name: Configure the project
      run: ./configure

    - name: Compile the project
      run: make

    - name: Verify binary file
      run: |
        if [ -f ./my_program ]; then
          echo "Binary file compiled successfully: ./my_program"
        else
          echo "Error: Binary file was not created!" >&2
          exit 1
        fi
