name: Build Debian Package

on:
  push:
    branches: [branchAutoPackage, master]
  pull_request:
    branches: [branchAutoPackage, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Switch to branch with configure.ac
      run: git checkout branchAutoPackage

    - name: Checkout debian directory from master
      run: git checkout master -- debian

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool build-essential devscripts debhelper curl

    - name: Download release tarball
      run: |
        curl -LJO https://github.com/holksen/L2/releases/download/v1.0/myprogram_1.0.orig.tar.gz

    - name: Generate configure script
      run: autoreconf -i

    - name: Configure the project
      run: ./configure --disable-dependency-tracking

    - name: Build Debian package
      run: |
        debuild -us -uc

    - name: Upload Debian Package
      uses: actions/upload-artifact@v3
      with:
        name: my_program-deb-package
        path: ../*.deb
