name: Build Debian Package

on:
  push:
    branches: [branchAutomake, branchAutoPackage, master]
  pull_request:
    branches: [branchAutomake, branchAutoPackage, master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout branchAutoPackage
      run: git checkout branchAutoPackage

    - name: Set up Build Environment
      run: |
        sudo apt update
        sudo apt install -y build-essential devscripts debhelper

    - name: Set up autotools
      run: sudo apt-get install -y automake autoconf

    - name: Generate configure script
      run: autoreconf -i

    - name: Build Debian package
      run: |
        debuild -us -uc

    - name: Upload Debian Package
      uses: actions/upload-artifact@v3
      with:
        name: my_program-deb-package
        path: ../*.deb
