name: Build Project

on: [push, pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: sudo apt-get install -y build-essential

      - name: Compile the project
        run: make
